apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ldl4u12tv-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ldl4u12tv-java-springboot-gitops